language: node_js

os:
  - osx

node_js:
  - node

install:
  - npm install

cache:
  directories:
    - "node_modules"

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - fossa init
  - fossa analyze

after_success:
  - cd <SOURCE_DIR> && fossa test

notifications:
  email:
    recipients:
      - bruno@logerfo.tk
    on_success: never # default: change
    on_failure: always
